apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoracao
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoracao.svc:9093"

    scrape_configs:
    
      - job_name: 'apis-services'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - shoes-eks
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: 'api--.|service--.|server--.'
            action: keep
          - source_labels: [__meta_kubernetes_service_label_port]
            regex: '9190'
            action: keep

      - job_name: 'login-services'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - ns-login
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: 'provider--.'
            action: keep
          - source_labels: [__meta_kubernetes_service_label_port]
            regex: '7080'
            action: keep

      - job_name: 'infra-services'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - ns-infra
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            regex: 'mysql|kafka-broker|redis|schema-registry|zoopecker'
            action: keep
          - source_labels: [__meta_kubernetes_service_label_port]
            regex: '3306|9092|6379|8081|2181'
            action: keep