apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoracao
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoracao.svc:9093"

    scrape_configs:
    
      - job_name: server--discovery-stack
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-server--discovery-stack.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: server--discovery-stack
    
      - job_name: server--config-service
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-server--config-service.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: server--config-service    
    
      - job_name: api--customer
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-api--customer.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: api--customer
    
      - job_name: api--product
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-api--product.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: api--product
    
      - job_name: api--order
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-api--order.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: api--order
    
      - job_name: bff--site-shoes
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-bff--site-shoes.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: bff--site-shoes
    
      - job_name: service--notification
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-service--notification.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: service--notification
    
      - job_name: service--payment
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'svc-service--payment.shoes-eks.svc.cluster.local:9190' ]
            labels:
              application: service--payment
    
      - job_name: provider--shoesclick-login
        scrape_interval: 5s
        metrics_path: /auth/metrics
        static_configs:
          - targets: [ 'svc-login.ns-login.svc.cluster.local:7080' ]
            labels:
              application: provider--shoesclick-login