{
 "title": "Shoes Click Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Clientes Criados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "customer_process_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pedidos Criados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "order_process_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Notificações enviadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "notification_process_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pagamentos Processados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "payment_process_total", "legendFormat": "__auto" }
   ]
  }
 ]
}